blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='blog_list'),
    path('<slug:slug>/',views.Blogdetails, name='blog_details'),
]

cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_details, name="cart_details"),
    # path('add', views.add_to_cart, name="add"),
    path('add-course', views.add_to_cart, name="add_course"),
    path('remove/<int:id>', views.remove_from_cart, name="remove"),
    path('clear/', views.clear_cart, name="clear")
]

course/urls.py
from django.urls import path
from . import views

app_name = 'course'

urlpatterns = [
    path('', views.CourseList.as_view(), name='courselist'),
    path('<slug:slug>/',views.CourseDetails, name='course_details'),
    path('learn/<slug:slug>/',views.LearnCourse, name='learn'),
    path('<int:course_id>/lecture/<int:id>/',views.LeesonView, name='learn_view')
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('_nested_admin/', include('nested_admin.urls')),
    path('admin/', admin.site.urls),
    path('',include('home.urls', namespace="home")),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('course/',include('course.urls', namespace="course")),
    path('tin-tuc/',include('blog.urls', namespace='blog')),
    path('thanh-toan/',include('vnpay.urls', namespace='vnpay')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

course/models.py
from django.db import models
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from autoslug import AutoSlugField

# Create your models here.

types = (
    ('Free', 'Free'),
    ('Paid', 'Paid')
)
class Type_course(models.Model):
    name = models.CharField(verbose_name = "Tên loại khóa học",max_length=150,blank=False, null=False)
    slug = AutoSlugField(populate_from='name',unique_with=['created'])
    created = models.DateTimeField(verbose_name = "Ngày tạo",auto_now_add=True)
    updated = models.DateTimeField(verbose_name = "Ngày chỉnh sửa gần nhất",auto_now=True)

    class Meta:
        verbose_name ="Danh mục khóa học"
        verbose_name_plural ="Danh mục khóa học"

    def get_absolute_path(self):
        return reverse('course:course_list') + f'?type_course={self.id}'

    def __str__(self):
        return self.name

class Course(models.Model):
    type_course = models.ForeignKey(Type_course, on_delete=models.CASCADE,related_name='courses') #Nếu type course bị xóa thì Course cũng sẽ bị xoá
    name = models.CharField(verbose_name = "Tên khóa học",max_length=1500,blank=False, null=False)
    slug = AutoSlugField(populate_from='name',unique_with=['created'])
    description = RichTextUploadingField(verbose_name = "Mô tả")
    type = models.CharField(verbose_name = "Loại khóa học",max_length=1500,choices=types, default='Free')
    price = models.FloatField(verbose_name = "Giá khóa học",default=0)
    image = models.ImageField(upload_to='media/course/%Y/%m/%d/', blank=False)
    video_intro = models.TextField(verbose_name = "Video giới thiệu",max_length=1500,default='')
    created = models.DateTimeField(verbose_name = "Ngày tạo",auto_now_add=True)
    updated = models.DateTimeField(verbose_name = "Ngày chỉnh sửa gần nhất",auto_now=True)
    class Meta:
        verbose_name ="Khóa học"
        verbose_name_plural ="Khóa học"
        index_together = ('id', 'slug')
        ordering = ('-created',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('course:course_details', kwargs={'slug': self.slug})

class Topic(models.Model):
    course = models.ForeignKey(Course,on_delete=models.CASCADE,related_name='topics')
    name = models.CharField(verbose_name = "Tên topic",max_length=150,blank=False, null=False)
    slug = AutoSlugField(populate_from='name',unique_with=['created'])
    created = models.DateTimeField(verbose_name = "Ngày tạo",auto_now_add=True)
    updated = models.DateTimeField(verbose_name = "Ngày chỉnh sửa gần nhất",auto_now=True)

    class Meta:
        # verbose_name ="Chủ đề"
        # verbose_name_plural ="Chủ đề"
        index_together = ('id', 'slug')
        ordering = ('-created',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('course:course_details', kwargs={'slug': self.slug})

class Lesson(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE,related_name='lessons') #khoa ngoai
    name = models.CharField(verbose_name = "Tên leeson",max_length=150,blank=False, null=False)
    slug = AutoSlugField(populate_from='name',unique_with=['created'])
    video = models.TextField(verbose_name = "Link video",blank=False, null=False)
    time = models.CharField(verbose_name = "Thời gian",max_length=150,blank=False, null=False)
    created = models.DateTimeField(verbose_name = "Ngày tạo",auto_now_add=True)
    updated = models.DateTimeField(verbose_name = "Ngày chỉnh sửa gần nhất",auto_now=True)

    class Meta:
        # verbose_name ="Bài học"
        # verbose_name_plural ="Bài học"
        index_together = ('id', 'slug')
        ordering = ('-created',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('course:course_details', kwargs={'slug': self.slug})

course/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from course.models import Course, Lesson, Topic
from orders.models import OrderItem
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.db.models import Count

# Create your views here.
class CourseList(generic.ListView):
    model = Course
    paginate_by = 10
    context_object_name = 'Courses'
    template_name = 'course_list.html'

    def get_queryset(self):
        Courses = Course.objects.all().order_by('created')
        return Courses

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

def CourseDetails(request, slug):
    status = 0
    course = Course.objects.get(slug=slug)
    order_item = OrderItem.objects.filter(user=request.user)
    
    for item in order_item:
        if course.id == item.course_id:
            status = 1

    # Lấy tổng số bài học (lessons) và tổng số chủ đề (topics)
    total_lessons = Lesson.objects.filter(topic__course=course).count()
    total_topics = Topic.objects.filter(course=course).count()

    return render(request, 'course_details.html', {'course': course, 'status': status, 'total_lessons': total_lessons, 'total_topics': total_topics})

@login_required
def LearnCourse(request, slug):
    authUser = 0
    course = Course.objects.get(slug = slug)
    topics = Topic.objects.filter(course_id = course.id).order_by('id')
    #lấy tất cả các lesson
    lesson_aray = []
    for topic in topics:
        for item in Lesson.objects.filter(topic_id = topic.id).order_by('id'):
            lesson_aray.append(item)
    first_lesson = lesson_aray[0]
    #Kiểm tra khóa học có đc mua hay chưa
    order_item = OrderItem.objects.filter(user = request.user)
    for item in order_item:
        if course.id == item.course_id:
            authUser = 1
    
    return render(request,'course_learn.html',
        {'course' : course,
        'topics' : topics,
        'lessons' : lesson_aray,
        'first_lesson' : first_lesson,
        'status' : authUser

    })

def LeesonView(request,course_id ,id ):
    course = Course.objects.get(id = course_id)
    topics = Topic.objects.filter(course_id = course.id).order_by('id')
    #lấy tất cả các lesson
    lesson_aray = []
    for topic in topics:
        for item in Lesson.objects.filter(topic_id = topic.id).order_by('id'):
            lesson_aray.append(item)
            if item.id == id:
                lesson_select = item
    
    #Kiểm tra khóa học có đc mua hay chưa
    order_item = OrderItem.objects.filter(user = request.user)
    for item in order_item:
        if course.id == item.course_id:
            authUser = 1
    
    first_lesson = lesson_select
    return render(request,'course_learn.html',
        {'course' : course,
        'topics' : topics,
        'lessons' : lesson_aray,
        'first_lesson' : first_lesson,
        'status' : authUser
    })

course/templates/course_details.html
{% extends 'header.html'%} {% block title%}{{course.name}}{% endblock title%}
{%block content %} {% load my_filter %} {% load static %} {% load humanize %}
<!-- course-details-area -->
<section class="c-details-area pt-30 pb-50">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-12">
        <div class="c-details-wrapper mr-25">
          <div class="c-details-thumb p-relative mb-40">
            <img src="/media/{{course.image}}" alt="details-bg" />
          </div>
          <div class="course-details-content mb-45">
            <div class="tpcourse__category mb-15">
              <ul class="tpcourse__price-list d-flex align-items-center">
                <li>
                  <a class="c-color-green" href="#">{{course.type_course}}</a>
                </li>
              </ul>
            </div>
            <div class="tpcourse__ava-title mb-25">
              <h4 class="c-details-title"><a href="#">{{course.name}}</a></h4>
            </div>
            <div class="tpcourse__meta course-details-list">
              <ul class="d-flex align-items-center">
                <li>
                  <div class="rating-gold d-flex align-items-center">
                    <p>4.7</p>
                    <i class="fi fi-ss-star"></i>
                    <i class="fi fi-ss-star"></i>
                    <i class="fi fi-ss-star"></i>
                    <i class="fi fi-ss-star"></i>
                    <i class="fi fi-rs-star"></i>
                    <span>(125)</span>
                  </div>
                </li>
              </ul>
            </div>
          </div>
          <div class="c-details-about mb-40">
            <h5 class="tp-c-details-title mb-20">Về khóa học này</h5>
            {{course.description|safe|linebreaks}}
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-12">
        <div class="c-details-sidebar">
          <div class="c-video-thumb p-relative mb-25">
            {{course.video_intro|safe}}
          </div>
          <div class="course-details-widget">
            <div class="cd-video-price">
              <h3 class="pricing-video text-center mb-15">
                {% if course.type == 'Free' %} Miễn Phí {% else %}
                {{course.price|currency}} {% endif %}
              </h3>
              <div class="cd-pricing-btn text-center mb-30">
                {% if course.type == 'Free' %}
                <a class="tp-vp-btn" href="/course/learn/{{ course.slug }}"
                  >Tham gia ngay</a
                >
                {% else %} {% if course.id in cart.keys %}
                <a class="tp-vp-btn-green" href="{% url 'cart:cart_details' %}"
                  >Xem giỏ hàng</a
                >
                {% elif status == 1 %}
                <a class="tp-vp-btn" href="/course/learn/{{ course.slug }}"
                  >Vào học ngay</a
                >
                {% else %}
                <form method="POST" action="{% url 'cart:add_course' %}">
                  {% csrf_token %}
                  <input type="hidden" name="course_id" value="{{course.id}}" />
                  <button
                    class="btn-course tp-vp-btn-green"
                    type="submit"
                    class="btn btn-primary"
                  >
                    Mua khóa học
                  </button>
                </form>
                {% endif %} {% endif %}
              </div>
            </div>
            <div class="cd-information mb-35">
              <ul>
                <li>
                  <i class="fa-light fa-calendars"></i> <label>Số Chương</label>
                  <span>{{total_lessons}}</span>
                </li>
                <li>
                  <i class="fi fi-rr-user"></i> <label>Số học viên</label>
                  <span>105</span>
                </li>
                <li>
                  <i class="fi fi-sr-stats"></i> <label>Trình độ</label>
                  <span>Bắt đầu học python</span>
                </li>
                <li>
                  <i class="fi fi-rr-comments"></i> <label>Ngôn ngữ</label>
                  <span>Python</span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- course-details-area-end -->
{% endblock content%}

course/templates/course_learn.html
{% extends 'header.html'%}
{% block title%}{{course.name}}{% endblock title%}
{% block content %}
{% load static %}
{% load humanize %}
{% if status == 1%}
    <!-- course-details-area -->
      <main>
      <!-- postbox area start -->
      <div class="postbox__area pt-20 pb-40">
         <div class="container-fluid pr-50 pl-50">
            <div class="row">
               <div class="col-xxl-8 col-xl-8 col-lg-7 col-md-12">
                  <div class="postbox__wrapper pr-20">
                     <article class="postbox__item format-image mb-60 transition-3">
                        <div class="postbox__thumb w-img mb-30">
                           {{ first_lesson.video | safe }}
                        </div>
                        <div class="postbox__content">
                           <div class="postbox__meta">
                              <span><i class="fi fi-rr-calendar"></i>{{ course.created|date }}</span>
                              <span><a href="#"><i class="fi fi-rr-user"></i>ADMIN</a></span>
                              <span><a href="#"><i class="fi fi-rr-comments"></i> 02 Comments</a></span>
                           </div>
                           <h3 class="postbox__title">
                              {{ first_lesson.name }}
                           </h3>
                           <div class="postbox__text">
                              <p>{{ course.description|safe}}</p>
                           </div>
                        </div>
                     </article>  
                  </div>
               </div>
               <div class="col-xxl-4 col-xl-4 col-lg-5 col-md-12">
                  <div class="sidebar__wrapper">
                     <div class="sidebar__widget mb-55">
                        <h3 class="sidebar__widget-title mb-5">Danh sách bài giảng</h3>
                        <div class="sidebar__widget-content">
                           <div class="sidebar__post rc__post">
                              {% for item in topics%}
                                 <div class="rc__post topic-border mb-5">
                                    <button class="collapsible"><i class="far fa-minus-square"></i> {{item.name}}</button>
                                    <div class="content-lesson">
                                          {% for lesson_item in lessons%}
                                             {% if lesson_item.topic_id == item.id%}
                                                <div class="leeson-title"><a href="{% url 'course:learn_view' course.id lesson_item.id %}"><i class="far fa-play-circle"></i> {{lesson_item.name}}</a></div>
                                             {% endif %}
                                          {% endfor %}
                                    </div>
                                 </div>
                              {% endfor %}
                           </div>
                        </div>
                     </div>
                     <div class="sidebar__widget mb-40">
                        <h3 class="sidebar__widget-title mb-10">Category</h3>
                        <div class="sidebar__widget-content">
                           <ul>
                              <li><a href="blog.html">Business <span>(14)</span></a></li>
                              <li><a href="blog.html">Cleaning <span>(19)</span></a></li>
                              <li><a href="blog.html">Consultant <span>(21)</span></a></li>
                              <li><a href="blog.html">Creative <span>(27)</span></a></li>
                              <li><a href="blog.html">Technology <span>(35)</span></a></li>
                           </ul>
                        </div>
                     </div>
                     <div class="sidebar__widget mb-40">
                        <h3 class="sidebar__widget-title mb-30">Tags</h3>
                        <div class="sidebar__widget-content">
                           <div class="tagcloud">
                              <a href="#">IT Solution</a>
                              <a href="#">Digital Marketing</a>
                              <a href="#">Software Training</a>
                              <a href="#">Art & Design</a>
                              <a href="#">Photography</a>
                              <a href="#">Music</a>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- postbox area end -->
   </main>
   <!-- course-details-area-end -->
{% else %}
   <h2 class="text-center">Xin lỗi bạn không có quyền truy cập vào khóa học này.</h2>
   <img class="img-access"src="{% static 'assets/img/you-are-not-allowed-to-access-this-page.png' %}">
{% endif %}
<script>
   var coll = document.getElementsByClassName("collapsible");
   var i;
   for (i = 0; i < coll.length; i++) {
   coll[i].addEventListener("click", function() {
      this.classList.toggle("active");
      var content = this.nextElementSibling;
      if (content.style.maxHeight){
      content.style.maxHeight = null;
      } else {
      content.style.maxHeight = content.scrollHeight + "px";
      }
   });
   }
</script>
{% endblock content%}

course/templates/course_list.html
{% extends 'header.html'%}
{% block title%}Các khóa học mới{% endblock title%}
{% block content %}
{% load my_filter %}
{% load static %}
{% load humanize %}
<!-- course-area -->
      <section class="course-area pb-120">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="section-title text-center mb-45">
                     <span class="tp-sub-title-box mb-15">Khóa học mới</span>
                     <h2 class="tp-section-title mb-20">Khám khóa các khóa học mới được cập nhật</h2>
                  </div>
               </div>
            </div>
            <div class="row mb-20">
                {% for course in Courses %}
                    <div class="col-xl-4 col-lg-6 col-md-6">
                        <div class="tpcourse mb-40">
                            <div class="tpcourse__thumb p-relative w-img fix">
                                <a href="{% url 'course:course_details' course.slug %}"><img src="/media/{{course.image}}" alt="course-thumb"></a>
                                <div class="tpcourse__tag">
                                <a href="{% url 'course:course_details' course.slug %}"><i class="fi fi-rr-heart"></i></a>
                                </div>
                                <div class="tpcourse__img-icon">
                                {% comment %} <img src="/media/{{course.image}}" alt="course-avata"> {% endcomment %}
                                </div>
                            </div>
                            <div class="tpcourse__content-2">
                                <div class="tpcourse__category mb-10">
                                <ul class="tpcourse__price-list d-flex align-items-center">
                                    <li><a class="c-color-yellow" href="{% url 'course:course_details' course.slug %}">{{course.type_course}}</a></li>
                                </ul>
                                </div>
                                <div class="tpcourse__ava-title mb-15">
                                <h4 class="tpcourse__title tp-cours-title-color"><a href="{% url 'course:course_details' course.slug %}">{{course.name}}</a></h4>
                                </div>
                                <div class="tpcourse__meta tpcourse__meta-gap pb-15 mb-15">
                                <ul class="d-flex align-items-center">
                                    <li><img src="{% static 'assets/img/icon/c-meta-01.png' %}" alt="meta-icon"> <span>35 Classes</span></li>
                                    <li><img src="{% static 'assets/img/icon/c-meta-02.png' %}" alt="meta-icon"> <span>291 Students</span></li>
                                </ul>
                                </div>
                                <div class="tpcourse__rating d-flex align-items-center justify-content-between">
                                <div class="tpcourse__rating-icon">
                                    <span>4.7</span>
                                    <i class="fi fi-ss-star"></i>
                                    <i class="fi fi-ss-star"></i>
                                    <i class="fi fi-ss-star"></i>
                                    <i class="fi fi-ss-star"></i>
                                    <i class="fi fi-rs-star"></i>
                                    <p>(125)</p>
                                </div>
                                <div class="tpcourse__pricing">
                                    {% if course.type == 'Free'%}
                                       <h5 class="price-title">
                                          MIỄN PHÍ
                                       </h5>
                                    {% else %}
                                       <h5 class="price-title">
                                          {{course.price|currency}}
                                       </h5>
                                    {% endif %}
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% if Courses|length != 0 %}
               <div class="basic-pagination">
                  <nav>
                     {% with page_obj as page %}
                        <ul>
                           {% if page.has_previous %}
                              <li>
                                 <a href="?page={{ page.previous_page_number }}">
                                    <i class="far fa-angle-left"></i>
                                 </a>
                              </li>
                           {% endif %}
                              <li>
                                 <a>{{ page.number }}</a>
                              </li>
                           {% if page.has_next %}
                              <li>
                                 <a href="?page={{ page.next_page_number }}">
                                    <i class="far fa-angle-right"></i>
                                 </a>
                              </li>
                           {% endif %}

                        </ul>
                     {% endwith %}
                  </nav>
               </div>
            {% endif %}
         </div>
      </section>
      <!-- course-area-end -->
{% endblock content%}