blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='blog_list'),
    path('<slug:slug>/',views.Blogdetails, name='blog_details'),
]

cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_details, name="cart_details"),
    # path('add', views.add_to_cart, name="add"),
    path('add-course', views.add_to_cart, name="add_course"),
    path('remove/<int:id>', views.remove_from_cart, name="remove"),
    path('clear/', views.clear_cart, name="clear")
]

course/urls.py
from django.urls import path
from . import views

app_name = 'course'

urlpatterns = [
    path('', views.CourseList.as_view(), name='courselist'),
    path('<slug:slug>/',views.CourseDetails, name='course_details'),
    path('learn/<slug:slug>/',views.LearnCourse, name='learn'),
    path('<int:course_id>/lecture/<int:id>/',views.LeesonView, name='learn_view')
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('_nested_admin/', include('nested_admin.urls')),
    path('admin/', admin.site.urls),
    path('',include('home.urls', namespace="home")),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('course/',include('course.urls', namespace="course")),
    path('tin-tuc/',include('blog.urls', namespace='blog')),
    path('thanh-toan/',include('vnpay.urls', namespace='vnpay')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'
urlpatterns = [
    path('place', views.CreateOrder.as_view(), name='place'),
    path('my-course', views.MyOrders.as_view(), name='my_course'),
    path('details/<int:pk>/', views.OrderDetails.as_view(), name='details'),
    path('invoice/<int:pk>/', views.OrderInvoice.as_view(), name='invoice')
]

cart/forms.py
from django import forms


class CartForm(forms.Form):
    course_id = forms.IntegerField(required=True, widget=forms.HiddenInput())

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from cart.cart import Cart
from course.models import Course
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from cart.forms import CartForm
# Create your views here.


@login_required
@require_POST
def add_to_cart(request):
    cart = Cart(request)
    form = CartForm(request.POST)
    if form.is_valid():
        course_id = form.cleaned_data['course_id']
        course = get_object_or_404(Course, id=course_id)
        cart.add(course_id, course.price)
        messages.success(request, f'{course.name} đã được thêm vào giỏ hàng.')
    return redirect('cart:cart_details')

@login_required
def cart_details(request):
    cart = Cart(request)
    courses = Course.objects.filter(pk__in=cart.cart.keys())
    total_price = 0
    for i in courses:
        total_price += i.price
    return render(request, 'cart/cart_details.html', {'cart_items': courses, 'total_price': total_price})


@login_required
def remove_from_cart(request, id):
    cart = Cart(request)
    cart.remove(str(id))
    return redirect('cart:cart_details')


@login_required
def clear_cart(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart:cart_details')

cart/templates/cart/cart_details.html
{% extends 'header.html' %} {% block title %} Giỏ hàng {% endblock title %}
{% block content %}
{% comment %} <h1 class="display-4 mt-4 text-center">Giỏ hàng</h1> {% endcomment %}
{% if cart_items %}
<!-- cart area -->
<section class="cart-area pt-100 pb-100">
  <div class="container">
    <div class="row">
     <div class="col-12">
           <form action="#">
              <div class="table-content table-responsive">
                <table class="table">
                  <thead>
                    <tr>
                        <th class="product-thumbnail">#</th>
                        <th class="cart-product-name">Tên khóa học</th>
                        <th class="product-price">Giá</th>
                        <th class="product-remove">Xóa</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for item in cart_items %}
                      <tr>
                          <td class="product-thumbnail"><a href="{% url 'course:course_details' item.slug %}"><img src="/media/{{ item.image }}" alt=""></a></td>
                          <td class="product-name"><a href="{% url 'course:course_details' item.slug %}"> {{ item.name }} </a></td>
                          <td class="product-price"><span class="amount"> {{item.price}} VNĐ</span></td>
                          <td class="product-remove"><a href="{% url 'cart:remove' item.id %}"><i class="fa fa-times"></i></a></td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
              <div class="row justify-content-end">
                <div class="col-md-5 ">
                      <div class="cart-page-total">
                          <h2>Tổng giỏ hàng  : {{ total_price }} VNĐ</h2>
                          <a class="tp-btn" href="{% url 'orders:place' %}">Thanh toán</a>
                      </div>
                </div>
              </div>
            </form>
      </div>
    </div>
  </div>
</section>
<!-- cart area end-->   
{% comment %} <div class="text-center">
  <a href="{% url 'cart:clear' %}" class="btn btn-warning">Làm sạch giỏ</a>
  <a href="{% url 'orders:place' %}" class="btn btn-success">Thanh Toán</a>
</div> {% endcomment %}
{% else %}
<div class="text-center mb-20">
  <h1 class="font-weight-light ">Giỏ hàng trống</h1>
  <a href="{% url 'store:product_list' %}" class="btn btn-secondary">
    Trở lại cửa hàng
  </a>
</div>
{% endif %}
<script>
  let inputs = document.querySelectorAll("input.form-control");
  inputs.forEach((i) => i.classList.add("form-control-sm"));
</script>
{% endblock content %}