accounts/urls.py
from django.urls import path, include
from accounts import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register', views.Register.as_view(), name='register'),
    path('profile', views.profile, name='profile'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='blog_list'),
    path('<slug:slug>/',views.Blogdetails, name='blog_details'),
]

cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_details, name="cart_details"),
    # path('add', views.add_to_cart, name="add"),
    path('add-course', views.add_to_cart, name="add_course"),
    path('remove/<int:id>', views.remove_from_cart, name="remove"),
    path('clear/', views.clear_cart, name="clear")
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('_nested_admin/', include('nested_admin.urls')),
    path('admin/', admin.site.urls),
    path('',include('home.urls', namespace="home")),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('course/',include('course.urls', namespace="course")),
    path('tin-tuc/',include('blog.urls', namespace='blog')),
    path('thanh-toan/',include('vnpay.urls', namespace='vnpay')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'
urlpatterns = [
    path('place', views.CreateOrder.as_view(), name='place'),
    path('my-course', views.MyOrders.as_view(), name='my_course'),
    path('details/<int:pk>/', views.OrderDetails.as_view(), name='details'),
    path('invoice/<int:pk>/', views.OrderInvoice.as_view(), name='invoice')
]

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.forms import modelform_factory, widgets
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

# Create your views here.


class Register(SuccessMessageMixin, generic.CreateView):
    form_class = UserCreationForm
    success_message = "Đăng ký thành công bạn có thể đăng nhập."
    template_name = "registration/register.html"
    success_url = reverse_lazy('login')


@login_required
def profile(req):
    UserEditForm = modelform_factory(get_user_model(), fields=('first_name', 'last_name', 'username'))
    form = UserEditForm(instance=req.user)
    if req.method == "POST":
        form = UserEditForm(instance=req.user, data=req.POST)
        if form.is_valid():
            form.save()
    return render(req, 'registration/profile.html', {'form': form})

accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock title %}</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
      <div class="container">
        <a href="http://127.0.0.1:8000/" class="navbar-brand">H&H Thời trang nam</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navigation">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a href="{% url 'store:product_list' %}" class="nav-link">
                <i class="fa fa-shopping-bag fa-lg mr-1"></i> Cửa hàng
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'store:categories_list' %}" class="nav-link">
                <i class="fa fa-shopping-basket fa-lg mr-1"></i> Thể loại
              </a>
            </li>
          </ul>
          <form action="/" class="inline-form mr-md-2 ml-auto">
            <div class="input-group">
              <input
                required
                type="text"
                name="name"
                placeholder="Tìm kiếm"
                class="form-control"
              />
              <div class="input-group-append">
                <button type="submit" class="btn-success btn btn-sm">
                  <i class="fa fa-search fa-lg"></i>
                </button>
              </div>
            </div>
          </form>
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'orders:my_course' %}" class="nav-link">
                <i class="fa fa-truck fa-lg mr-1"></i> Đơn hàng
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'cart:cart_details' %}" class="nav-link">
                <i class="fa fa-shopping-cart fa-lg"></i>
                <span class="badge badge-secondary">
                  {% if cart %} {{cart|length}} {% else %} 0 {% endif%}
                </span>
              </a>
            </li>
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle mb-0" data-toggle="dropdown">
                {{request.user}}
              </a>
              <div class="dropdown-menu">
                <a href="{% url 'profile'%}" class="dropdown-item">Thông tin cá nhân</a>
                <a href="{% url 'password_change'%}" class="dropdown-item"> Đổi mật khẩu</a>
                <a href="{% url 'logout' %}" class="dropdown-item">đăng xuất</a>
              </div>
            </li>
            {% else %}
            <li class="nav-item">
              <a href="{% url 'login' %}" class="nav-link">
                <i class="fa fa-sign-in fa-lg"></i> Đăng nhập
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'register' %}" class="nav-link">
                <i class="fa fa-user-plus fa-lg"></i> Đăng ký
              </a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% if messages %}
      <div class="alert alert-success my-2">
        {% for message in messages %} {{message}} {% endfor %}
      </div>
      {% endif %} {% block content %} {% endblock content %}
    </div>
  </body>
</html>

accounts/templates/header.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title%}{% endblock title%}</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Place favicon.ico in the root directory -->
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.png' %}">

  <!-- CSS here -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'css/meanmenu.css' %}">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">
  <link rel="stylesheet" href="{% static 'css/slick.css' %}">
  <link rel="stylesheet" href="{% static 'css/backtotop.css' %}">
  <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
  <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
  <link rel="stylesheet" href="{% static 'css/ui-icon.css' %}">
  <link rel="stylesheet" href="{% static 'css/elegentfonts.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome-pro.css' %}">
  <link rel="stylesheet" href="{% static 'css/spacing.css' %}">
  <link rel="stylesheet" href="{% static 'css/mycss.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
<!--[if lte IE 9]>
      <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
      <![endif]-->


   <!-- pre loader area start -->
   <div id="loading">
      <div id="loading-center">
         <div id="loading-center-absolute">
            <!-- loading content here -->
         </div>
      </div>
   </div>
   <!-- pre loader area end -->

   <!-- back to top start -->
   <div class="progress-wrap">
      <svg class="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
         <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98" />
      </svg>
   </div>
   <!-- back to top end -->

   <!-- header area start -->
   <header class="header_white_area d-none d-xl-block">
      <div class="header__area pt-40 pb-5">
         <div class="main-header" id="header-sticky">
            <div class="container">
               <div class="row align-items-center justify-content-between">
                  <div class="col-xxl-7 col-xl-6 col-lg-6 col-md-5 col-6">
                     <div class="logo-area d-flex align-items-center">
                        <div class="logo">
                           <a href="http://127.0.0.1:8000/">
                              <img src="{% static 'assets/img/logo/logo-black.png '%}" alt="logo">
                           </a>
                        </div>
                     </div>
                  </div>
                  <div class="col-xxl-5 col-lg-6 col-md-7">
                     <div class="header-right header-right-box">
                        <div class="header-search-box">
                           <form action="/">
                              <div class="search-input">
                                 <input required name="name" type="text" placeholder="Tìm kiếm khóa học">
                                 <button class="header-search-btn"><i class="fi fi-rs-search mr-5"></i> Tìm kiếm...</button>
                              </div>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="row">
                  <div class="col-xxl-9 col-xl-9 col-lg-6 text-start">
                     <div class="main-menu main-menu-white">
                        <nav id="mobile-menu">
                           <ul>
                              <li>
                                 <a href="http://127.0.0.1:8000/">Trang chủ</a>
                              </li>
                             <li>
                                 <a href="/course">Khóa học</a>
                              </li>
                              <li>
                                 <a href="/tin-tuc">Tin tức</a>
                              </li>
                              <li>
                                 <a href="index.html">Liên hệ</a>
                              </li>
                           </ul>
                        </nav>
                     </div>
                  </div>
                  <div class="col-xxl-3 col-xl-3 col-lg-6 d-flex align-items-center justify-content-end">
                     <div class="header-meta-green">
                     {% if user.is_authenticated %}
                        <ul>
                           
                           <li><a href="{% url 'profile'%}"><i class="fi fi-rr-user"></i></a></li>
                           <li><a href="{% url 'cart:cart_details' %}"><i class="fi fi-rr-shopping-bag"></i></a></li>
                           <li><a href="#" class="tp-menu-toggle d-xl-none"><i class="icon_ul"></i></a></li>
                           <a class="ml-20 tp-btn" href="{% url 'orders:my_course' %}">Vào học</a>
                        </ul>
                     {% else %}
                        <ul>
                           <li><a href="{% url 'login' %}"><i class="fi fi-rr-user"></i></a></li>
                           <li><a href="{% url 'cart:cart_details' %}"><i class="fi fi-rr-shopping-bag"></i></a></li>
                           <li><a href="#" class="tp-menu-toggle d-xl-none"><i class="icon_ul"></i></a></li>
                        </ul>
                     {% endif %}
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </header>

   <div class="mobile-header-area d-xl-none">
      <div class="container">
         <div class="row align-items-center">
            <div class="col-md-6 col-5">
               <div class="logo">
                  <a href="index.html">
                     <img src="{% static 'assets/img/logo/logo-black.png '%}" alt="logo">
                  </a>
               </div>
            </div>
            <div class="col-md-6 col-7 d-flex align-items-center justify-content-end">
               <div class="header-meta-green text-end">
                  {% if user.is_authenticated %}
                     <ul>
                        <li><a href="{% url 'profile'%}"><i class="fi fi-rr-user"></i></a></li>
                        <li><a href="/cart"><i class="fi fi-rr-shopping-bag"></i></a></li>
                        <li><a href="#" class="tp-menu-toggle d-xl-none"><i class="icon_ul"></i></a></li>
                     </ul>
                  {% else %}
                     <ul>
                        <li><a href="{% url 'login' %}"><i class="fi fi-rr-user"></i></a></li>
                        <li><a href="/cart"><i class="fi fi-rr-shopping-bag"></i></a></li>
                        <li><a href="#" class="tp-menu-toggle d-xl-none"><i class="icon_ul"></i></a></li>
                     </ul>
                  {% endif %}
               </div>
            </div>
         </div>
      </div>
   </div>

   <!-- header area end -->
   <div class="tp-sidebar-menu">
      <button class="sidebar-close"><i class="icon_close"></i></button>
      <div class="side-logo mb-30">
         <a href="index.html"><img src="{% static 'assets/img/logo/logo-black.png '%}" alt="logo"></a>
      </div>
      <div class="mobile-menu"></div>
      <div class="sidebar-info">
         <h4 class="mb-15">Thông tin liên hệ</h4>
         <ul class="side_circle">
            <li>37 Duy Tân, Nam Từ Liêm, Hà Nội</li>
            <li><a href="tel:0999999999">0999 999 999</a></li>
            <li><a href="mailto:sang@gmail.com">sang@gmail.com</a></li>
         </ul>
         <div class="side-social">
            <a href="#"><i class="fab fa-facebook-f"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-linkedin"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
         </div>
      </div>
   </div>
   <div class="body-overlay"></div>

  <!-- header area end -->
  {% block content %} {% endblock content %}
  <!-- phần body -->
  <!-- footer-area -->
  <footer>
    <div class="footer-bg theme-bg bg-bottom" data-background="{% static 'assets/img/bg/shape-bg-02.png' %}">
      <div class="f-border pt-115 pb-70">
        <div class="container">
          <div class="row">
            <div class="col-xl-2 col-md-4  col-6">
              <div class="footer-widget footer-3-col-1 mb-50">
                <div class="footer-widget__text mb-35">
                  <h3 class="footer-widget__title">Về chúng tôi</h3>
                </div>
                <div class="footer-widget__link">
                  <ul>
                    <li><a href="#">Liên hệ</a></li>
                    <li><a href="#">Bài viết</a></li>
                    <li><a href="#">Khóa học</a></li>
                    <li><a href="#">Nghề nghiệp</a></li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="col-xl-5 col-md-4 col-6">
              <div class="footer-widget footer-3-col-2 mb-50">
               <div class="footer-widget__text mb-35">
                  <h3 class="footer-widget__title">Học Online cùng EROPA</h3>
                </div>
                <img src="{% static 'assets/img/hoc-online.jpg' %}">
              </div>
            </div>
            <div class="col-xl-5 col-md-4 col-6">
               <div class="footer-widget footer-3-col-2 mb-50">
                  <div class="footer-widget__text mb-35">
                     <h3 class="footer-widget__title">Trụ sở chính</h3>
                   </div>
                   <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d77238.49301641625!2d105.7662951701907!3d21.09506709919357!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135abb158a2305d%3A0x5c357d21c785ea3d!2zVHLGsOG7nW5nIMSQ4bqhaSBo4buNYyDEkGnhu4duIEzhu7Fj!5e0!3m2!1svi!2s!4v1670790152962!5m2!1svi!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                 </div>
            </div>
          </div>
        </div>
      </div>
      <div class="f-copyright pt-60 pb-40">
        <div class="container">
          <div class="row text-center text-lg-start">
            <div class="col-xl-3 col-lg-3">
              <div class="f-copyright__logo mb-30">
                <a href="#"><img src="{% static 'assets/img/logo/Logo.png' %}" alt="logo"></a>
              </div>
            </div>
            <div class="col-xl-6 col-lg-5">
              <div class="f-copyright__text text-center mb-30">
                <span>Nguyễn Sang© 2022, All Rights Reserved</span>
              </div>
            </div>
            <div class="col-xl-3 col-lg-4">
              <div class="f-copyright__social-area mb-20 text-lg-end">
                <a href="https://www.facebook.com/sanglynn.1609/" target="_blank"><i class="fa-brands fa-facebook-square"></i></a>
                <a href="https://www.facebook.com/sanglynn.1609/" target="_blank"><i class="fa-brands fa-youtube"></i></a>
                <a href="https://www.facebook.com/sanglynn.1609/" target="_blank"><i class="fi fi-rr-basketball"></i></a>
                <a href="https://www.facebook.com/sanglynn.1609/" target="_blank"><i class="fa-brands fa-whatsapp"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- footer-area-end -->
  <!-- JS here -->
  <script>
      function number_format(number, decimals, dec_point, thousands_sep) {
      // *     example: number_format(1234.56, 2, ',', ' ');
      // *     return: '1 234,56'
      number = (number + '').replace(',', '').replace(' ', '');
      var n = !isFinite(+number) ? 0 : +number,
        prec = !isFinite(+decimals) ? 0 : Math.abs(decimals),
        sep = (typeof thousands_sep === 'undefined') ? ',' : thousands_sep,
        dec = (typeof dec_point === 'undefined') ? '.' : dec_point,
        s = '',
        toFixedFix = function(n, prec) {
          var k = Math.pow(10, prec);
          return '' + Math.round(n * k) / k;
        };
      // Fix for IE parseFloat(0.55).toFixed(0) = 0;
      s = (prec ? toFixedFix(n, prec) : '' + Math.round(n)).split('.');
      if (s[0].length > 3) {
        s[0] = s[0].replace(/\B(?=(?:\d{3})+(?!\d))/g, sep);
      }
      if ((s[1] || '').length < prec) {
        s[1] = s[1] || '';
        s[1] += new Array(prec - s[1].length + 1).join('0');
      }
      return s.join(dec);
    }
  </script>
  <script src="{% static 'js/jquery.js' %}"></script>
  <script src="{% static 'js/waypoints.js' %}"></script>
  <script src="{% static 'js/bootstrap-bundle.js' %}"></script>
  <script src="{% static 'js/meanmenu.js' %}"></script>
  <script src="{% static 'js/slick.js' %}"></script>
  <script src="{% static 'js/magnific-popup.js' %}"></script>
  <script src="{% static 'js/parallax.js' %}"></script>
  <script src="{% static 'js/backtotop.js' %}"></script>
  <script src="{% static 'js/nice-select.js' %}"></script>
  <script src="{% static 'js/counterup.js' %}"></script>
  <script src="{% static 'js/wow.js' %}"></script>
  <script src="{% static 'js/isotope-pkgd.js' %}"></script>
  <script src="{% static 'js/imagesloaded-pkgd.js' %}"></script>
  <script src="{% static 'js/ajax-form.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
</body>

</html>