blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='blog_list'),
    path('<slug:slug>/',views.Blogdetails, name='blog_details'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('_nested_admin/', include('nested_admin.urls')),
    path('admin/', admin.site.urls),
    path('',include('home.urls', namespace="home")),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('course/',include('course.urls', namespace="course")),
    path('tin-tuc/',include('blog.urls', namespace='blog')),
    path('thanh-toan/',include('vnpay.urls', namespace='vnpay')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

vnpay/urls.py
from django.urls import path
from vnpay import views

app_name = 'vnpay'

urlpatterns = [
    path('view-payment/<int:id>', views.viewpay, name='view-payment'),
    path('payment/<int:id>', views.payment, name='payment'),
    path('payment-details', views.paymentSave, name='payment-details')
]

vnpay/models.py
from django.db import models

# Create your models here.
class Payment(models.Model):
    vnp_TxnRef = models.CharField(verbose_name = "Mã đơn hàng",max_length=150,blank=False, null=False)
    vnp_Amount = models.CharField(verbose_name = "Tổng đơn hàng",max_length=150,blank=False, null=False)
    vnp_BankCode = models.CharField(verbose_name = "Ngân hàng",max_length=150,blank=False, null=False)
    vnp_BankTranNo = models.CharField(verbose_name = "Mã giao dịch",max_length=150,blank=False, null=False)
    vnp_CardType = models.CharField(verbose_name = "Loại thanh toán",max_length=150,blank=False, null=False)
    vnp_OrderInfo = models.CharField(verbose_name = "Thông tin thanh toán",max_length=150,blank=False, null=False)
    vnp_PayDate = models.CharField(verbose_name = "Ngày thanh toán",max_length=150,blank=False, null=False)
    vnp_ResponseCode = models.CharField(verbose_name = "Mã Trả về",max_length=150,blank=False, null=False)

    created = models.DateTimeField(verbose_name = "Ngày tạo",auto_now_add=True)
    updated = models.DateTimeField(verbose_name = "Ngày chỉnh sửa gần nhất",auto_now=True)

    class Meta:
        verbose_name ="Danh sách hóa đơn thanh toán"
        verbose_name_plural ="Danh sách hóa đơn thanh toán"


    def __str__(self):
        return self.vnp_TxnRef

vnpay/forms.py
from django import forms


class PaymentForm(forms.Form):

    order_id = forms.CharField(max_length=250)
    order_type = forms.CharField(max_length=20)
    amount = forms.IntegerField()
    order_desc = forms.CharField(max_length=100)
    bank_code = forms.CharField(max_length=20, required=False)
    language = forms.CharField(max_length=2)

vnpay/views.py
import hashlib
import hmac
import urllib
import urllib.parse
import urllib.request
from datetime import datetime
from django.conf import settings
from django.shortcuts import render, redirect
from orders.models import Order
from vnpay.models import Payment

from vnpay.forms import PaymentForm
from vnpay.vnpay import vnpay


def index(request):
    return render(request, "index.html", {"title": "Danh sách demo"})


def hmacsha512(key, data):
    byteKey = key.encode('utf-8')
    byteData = data.encode('utf-8')
    return hmac.new(byteKey, byteData, hashlib.sha512).hexdigest()

def paymentSave(request):
    a1 = request.GET['vnp_TxnRef']
    a2 = request.GET['vnp_Amount']
    a3 = request.GET['vnp_BankCode']
    a4 = request.GET['vnp_BankTranNo']
    a5 = request.GET['vnp_CardType']
    a6 = request.GET['vnp_OrderInfo']
    a7 = request.GET['vnp_PayDate']
    a8 = request.GET['vnp_ResponseCode']
    
    payment = Payment(vnp_TxnRef = a1, vnp_Amount = a2, vnp_BankCode = a3, vnp_BankTranNo = a4, vnp_CardType = a5, vnp_OrderInfo = a6, vnp_PayDate = a7, vnp_ResponseCode = a8)
    payment.save()

    order = Order.objects.get(id = a1)
    order.status = 1
    order.save()
    
    return redirect('course:courselist')

def viewpay(request, id):
    order = Order.objects.get(id = id)
    return render(request,'payment.html', {'order' : order})


def payment(request,id):
    order = Order.objects.get(id = id)

    order_type = 'billpayment'
    order_id = order.id
    amount = order.total_price
    order_desc = "Thanh toan cho don hang "+str(order.id)+" so tien : "+str(order.total_price)
    bank_code = ""
    language = "vn"
    ipaddr = get_client_ip(request)
    # Build URL Payment
    vnp = vnpay()
    vnp.requestData['vnp_Version'] = '2.1.0'
    vnp.requestData['vnp_Command'] = 'pay'
    vnp.requestData['vnp_TmnCode'] = settings.VNPAY_TMN_CODE
    vnp.requestData['vnp_Amount'] = amount * 100
    vnp.requestData['vnp_CurrCode'] = 'VND'
    vnp.requestData['vnp_TxnRef'] = order_id
    vnp.requestData['vnp_OrderInfo'] = order_desc
    vnp.requestData['vnp_OrderType'] = order_type
    # Check language, default: vn
    if language and language != '':
        vnp.requestData['vnp_Locale'] = language
    else:
        vnp.requestData['vnp_Locale'] = 'vn'
        # Check bank_code, if bank_code is empty, customer will be selected bank on VNPAY
    if bank_code and bank_code != "":
        vnp.requestData['vnp_BankCode'] = bank_code

    vnp.requestData['vnp_CreateDate'] = datetime.now().strftime('%Y%m%d%H%M%S')  # 2015 04 10 06 30 22
    vnp.requestData['vnp_IpAddr'] = ipaddr
    vnp.requestData['vnp_ReturnUrl'] = settings.VNPAY_RETURN_URL
    vnpay_payment_url = vnp.get_payment_url(settings.VNPAY_PAYMENT_URL, settings.VNPAY_HASH_SECRET_KEY)
    print(vnpay_payment_url)
    return redirect(vnpay_payment_url)

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


# def payment_ipn(request):
#     inputData = request.GET
#     if inputData:
#         vnp = vnpay()
#         vnp.responseData = inputData.dict()
#         order_id = inputData['vnp_TxnRef']
#         amount = inputData['vnp_Amount']
#         order_desc = inputData['vnp_OrderInfo']
#         vnp_TransactionNo = inputData['vnp_TransactionNo']
#         vnp_ResponseCode = inputData['vnp_ResponseCode']
#         vnp_TmnCode = inputData['vnp_TmnCode']
#         vnp_PayDate = inputData['vnp_PayDate']
#         vnp_BankCode = inputData['vnp_BankCode']
#         vnp_CardType = inputData['vnp_CardType']
#         if vnp.validate_response(settings.VNPAY_HASH_SECRET_KEY):
#             # Check & Update Order Status in your Database
#             # Your code here
#             firstTimeUpdate = True
#             totalamount = True
#             if totalamount:
#                 if firstTimeUpdate:
#                     if vnp_ResponseCode == '00':
#                         print('Payment Success. Your code implement here')
#                     else:
#                         print('Payment Error. Your code implement here')

#                     # Return VNPAY: Merchant update success
#                     result = JsonResponse({'RspCode': '00', 'Message': 'Confirm Success'})
#                 else:
#                     # Already Update
#                     result = JsonResponse({'RspCode': '02', 'Message': 'Order Already Update'})
#             else:
#                 # invalid amount
#                 result = JsonResponse({'RspCode': '04', 'Message': 'invalid amount'})
#         else:
#             # Invalid Signature
#             result = JsonResponse({'RspCode': '97', 'Message': 'Invalid Signature'})
#     else:
#         result = JsonResponse({'RspCode': '99', 'Message': 'Invalid request'})

#     return result


# def payment_return(request):
#     inputData = request.GET
#     if inputData:
#         vnp = vnpay()
#         vnp.responseData = inputData.dict()
#         order_id = inputData['vnp_TxnRef']
#         amount = int(inputData['vnp_Amount']) / 100
#         order_desc = inputData['vnp_OrderInfo']
#         vnp_TransactionNo = inputData['vnp_TransactionNo']
#         vnp_ResponseCode = inputData['vnp_ResponseCode']
#         vnp_TmnCode = inputData['vnp_TmnCode']
#         vnp_PayDate = inputData['vnp_PayDate']
#         vnp_BankCode = inputData['vnp_BankCode']
#         vnp_CardType = inputData['vnp_CardType']
#         if vnp.validate_response(settings.VNPAY_HASH_SECRET_KEY):
#             if vnp_ResponseCode == "00":
#                 return render(request, "payment_return.html", {"title": "Kết quả thanh toán",
#                                                                "result": "Thành công", "order_id": order_id,
#                                                                "amount": amount,
#                                                                "order_desc": order_desc,
#                                                                "vnp_TransactionNo": vnp_TransactionNo,
#                                                                "vnp_ResponseCode": vnp_ResponseCode})
#             else:
#                 return render(request, "payment_return.html", {"title": "Kết quả thanh toán",
#                                                                "result": "Lỗi", "order_id": order_id,
#                                                                "amount": amount,
#                                                                "order_desc": order_desc,
#                                                                "vnp_TransactionNo": vnp_TransactionNo,
#                                                                "vnp_ResponseCode": vnp_ResponseCode})
#         else:
#             return render(request, "payment_return.html",
#                           {"title": "Kết quả thanh toán", "result": "Lỗi", "order_id": order_id, "amount": amount,
#                            "order_desc": order_desc, "vnp_TransactionNo": vnp_TransactionNo,
#                            "vnp_ResponseCode": vnp_ResponseCode, "msg": "Sai checksum"})
#     else:
#         return render(request, "payment_return.html", {"title": "Kết quả thanh toán", "result": ""})


# def query(request):
#     if request.method == 'GET':
#         return render(request, "query.html", {"title": "Kiểm tra kết quả giao dịch"})
#     else:
#         # Add paramter
#         vnp = vnpay()
#         vnp.requestData = {}
#         vnp.requestData['vnp_Command'] = 'querydr'
#         vnp.requestData['vnp_Version'] = '2.1.0'
#         vnp.requestData['vnp_TmnCode'] = settings.VNPAY_TMN_CODE
#         vnp.requestData['vnp_TxnRef'] = request.POST['order_id']
#         vnp.requestData['vnp_OrderInfo'] = 'Kiem tra ket qua GD OrderId:' + request.POST['order_id']
#         vnp.requestData['vnp_TransDate'] = request.POST['trans_date']  # 20150410063022
#         vnp.requestData['vnp_CreateDate'] = datetime.now().strftime('%Y%m%d%H%M%S')  # 20150410063022
#         vnp.requestData['vnp_IpAddr'] = get_client_ip(request)
#         requestUrl = vnp.get_payment_url(settings.VNPAY_API_URL, settings.VNPAY_HASH_SECRET_KEY)
#         responseData = urllib.request.urlopen(requestUrl).read().decode()
#         print('RequestURL:' + requestUrl)
#         print('VNPAY Response:' + responseData)
#         data = responseData.split('&')
#         for x in data:
#             tmp = x.split('=')
#             if len(tmp) == 2:
#                 vnp.responseData[tmp[0]] = urllib.parse.unquote(tmp[1]).replace('+', ' ')

#         print('Validate data from VNPAY:' + str(vnp.validate_response(settings.VNPAY_HASH_SECRET_KEY)))
#         return render(request, "query.html", {"title": "Kiểm tra kết quả giao dịch", "data": vnp.responseData})


# def refund(request):
#     return render(request, "refund.html", {"title": "Gửi yêu cầu hoàn tiền"})

vnpay/templates/base_layout.html
<!DOCTYPE html>
<html lang="en">{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="VNPAY PAYMENT GATEWAY DEMO">
    <meta name="author" content="VNPAY">
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet"/>
    <!-- Custom styles for this template -->
    <link href="{% static "css/jumbotron-narrow.css" %}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <!--[if lt IE 9]><script src="{% static "js/ie8-responsive-file-warning.js" %}"></script><![endif]-->
    <script src="{% static "js/ie-emulation-modes-warning.js" %}"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>
</head>
<body>
<div class="container">
    <div class="header clearfix">
       {% comment %} <nav>
            <ul class="nav nav-pills pull-right">
                <li role="presentation"><a href="/">Danh sách</a></li>
                <li role="presentation" class="active"><a href="/CreateOrder">Tạo mới</a></li>

            </ul>
        </nav>{% endcomment %}
    </div>
    {% block content %}
    {% endblock %}

    <footer class="footer">
        <p>&copy; VNPAY {% now "Y" %}</p>
    </footer>
</div> <!-- /container -->


<link href="https://pay.vnpay.vn/lib/vnpay/vnpay.css" rel="stylesheet"/>
<script src="https://pay.vnpay.vn/lib/vnpay/vnpay.js"></script>

<script type="text/javascript">
    $("#btnPopup").click(function () {
        var postData = $("#frmCreateOrder").serialize();
        var submitUrl = $("#frmCreateOrder").attr("action");
        $.ajax({
            type: "POST",
            url: submitUrl,
            data: postData,
            dataType: 'JSON',
            success: function (x) {
                if (x.code === '00') {
                    vnpay.open({width: 480, height: 600, url: x.data});
                    return false;
                } else {
                    alert(x.Message);
                }
            }
        });
        return false;
    });
</script>


<script>

</script>
</body>
</html>

vnpay/templates/index.html
{% extends "base_layout.html" %}
{% block content %}
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">{{ title }}</div>
        <div class="table-responsive">
            <ul class="list-group">
                <i class="list-group-item"><a href="{% url "payment" %}">Demo Thanh toán</a></i>
                <i class="list-group-item"><a href="{% url "query" %}">Demo Query (Kiểm tra kết quả Giao dịch tại
                    VNPAY)</a></i>
                <i class="list-group-item"><a href="{% url "refund" %}">Demo Refund (Gửi yêu cầu hoàn tiền cho giao
                    dịch)</a></i>
            </ul>
        </div>
    </div>
{% endblock %}

vnpay/templates/payment.html
{% extends "base_layout.html" %}
{% block content %}

    <h3>Thanh toán VN Pay đơn hàng {{ order.id }}</h3>
    <div class="table-responsive">
        <form action="{% url "vnpay:payment" %}" id="create_form" method="post">
            <div class="form-group">
                <label for="language">Loại hàng hóa </label>
                <select name="order_type" id="order_type" class="form-control">
                    <option selected value="billpayment">Thanh toán hóa đơn</option>
                </select>
            </div>
            <div class="form-group">
                <label for="order_id">Mã hóa đơn</label>
                <input readonly class="form-control" id="order_id" name="order_id" type="text" value="{{ order.id }}"/>
            </div>
            <div class="form-group">
                <label for="amount">Số tiền</label>
                <input readonly class="form-control" id="amount" name="amount" type="number" value="{{ order.total_price }}"/>
            </div>
            <div class="form-group">
                <label for="order_desc">Nội dung thanh toán</label>
                <textarea readonly class="form-control" cols="20" id="order_desc" name="order_desc" rows="2">Thanh toan don hang so {{ order.id }} so tien {{ order.total_price }} thoi gian : {% now "d-m-Y H:i:s" %}</textarea>
            </div>
            <div class="form-group">
                <label for="bank_code">Ngân hàng</label>
                <select name="bank_code" id="bank_code" class="form-control">
                    <option value="">Không chọn</option>
                    <option value="NCB"> Ngan hang NCB</option>
                    <option value="AGRIBANK"> Ngan hang Agribank</option>
                    <option value="SCB"> Ngan hang SCB</option>
                    <option value="SACOMBANK">Ngan hang SacomBank</option>
                    <option value="EXIMBANK"> Ngan hang EximBank</option>
                    <option value="MSBANK"> Ngan hang MSBANK</option>
                    <option value="NAMABANK"> Ngan hang NamABank</option>
                    <option value="VNMART"> Vi dien tu VnMart</option>
                    <option value="VIETINBANK">Ngan hang Vietinbank</option>
                    <option value="VIETCOMBANK"> Ngan hang VCB</option>
                    <option value="HDBANK">Ngan hang HDBank</option>
                    <option value="DONGABANK"> Ngan hang Dong A</option>
                    <option value="TPBANK"> Ngân hàng TPBank</option>
                    <option value="OJB"> Ngân hàng OceanBank</option>
                    <option value="BIDV"> Ngân hàng BIDV</option>
                    <option value="TECHCOMBANK"> Ngân hàng Techcombank</option>
                    <option value="VPBANK"> Ngan hang VPBank</option>
                    <option value="MBBANK"> Ngan hang MBBank</option>
                    <option value="ACB"> Ngan hang ACB</option>
                    <option value="OCB"> Ngan hang OCB</option>
                    <option value="IVB"> Ngan hang IVB</option>
                    <option value="VISA"> Thanh toan qua VISA/MASTER</option>
                </select>
            </div>

            <button type="submit" class="btn btn-default">Thanh toán Redirect</button>
            {% csrf_token %}
            <div class="form-group"></div>
        </form>
    </div>
{% endblock %}

vnpay/templates/payment_return.html
{% extends "base_layout.html" %}
{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">{{ title }}: {{ result }}</div>
        <div class="panel-body">
            <p>order_id:{{ order_id }}</p>
            <p>amount:{{ amount }}</p>
            <p>order_desc:{{ order_desc }}</p>
            <p>vnp_TransactionNo:{{ vnp_TransactionNo }}</p>
            {% if vnp_ResponseCode == '00' %}
                <p>vnp_ResponseCode: {{ vnp_ResponseCode }} - Thành công</p>
            {% else %}
                <p>vnp_ResponseCode: {{ vnp_ResponseCode }} - Lỗi</p>
            {% endif %}
            {% if msg %}
                <p class="alert-warning"> {{ msg }}</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

vnpay/templates/query.html
{% extends "base_layout.html" %}
{% block content %}

    <h3>{{ title }}</h3>
    <div class="table-responsive">
        <form action="{% url "query" %}" id="create_form" method="post">

            <div class="form-group">
                <label for="order_id">Mã hóa đơn</label>
                <input class="form-control" id="order_id"
                       name="order_id" type="text"/>
            </div>
            <div class="form-group">
                <label for="order_id">Thời gian thanh toán</label>
                <input class="form-control" id="trans_date"
                       name="trans_date" type="text"/>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Query</button>
            </div>

            {% csrf_token %}
        </form>
        {% if data %}
            {% for key,val in data.items %}
             <div class="form-group">
                <label>{{ key }}: {{ val }}</label>
            </div>
            {% endfor %}

        {% endif %}
    </div>

{% endblock %}

vnpay/templates/refund.html
{% extends "base_layout.html" %}
{% block content %}

    <h3>{{ title }}</h3>
    <div class="table-responsive">
        <form action="{% url "query" %}" id="create_form" method="post">

            <div class="form-group">
                <label for="order_id">Mã hóa đơn</label>
                <input class="form-control" id="order_id"
                       name="order_id" type="text"/>
            </div>
            <div class="form-group">
                <label for="order_id">Số tiền hoàn trả</label>
                <input class="form-control" id="amount"
                       name="amount" type="text"/>
            </div>
            <div class="form-group">
                <label for="order_id">Nội dung/lý do hoàn trả</label>
                <input class="form-control" id="order_desc"
                       name="order_desc" type="text"/>
            </div>
            <div class="form-group">
                <label for="order_id">Thời gian Thanh toán</label>
                <input class="form-control" id="trans_date"
                       name="trans_date" type="text"/>
            </div>
            <div class="form-group">
                <label for="order_id">Ngày GD</label>
                <input class="form-control" id="trans_date"
                       name="trans_date" type="text"/>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Query</button>
            </div>
            {% csrf_token %}
        </form>
    </div>

{% endblock %}